grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 5
    verbose: 2
model_selection:
  module_1:
    class: RandomForestClassifier
    module: sklearn.ensemble
    params:
      n_estimators: 100
      max_features: 1.0
      max_depth: 10
      max_samples: 0.5
    search_param_grid:
      n_estimators:
      - 100
      max_features:
      - 1.0
      max_depth:
      - 10
      max_samples:
      - 0.5