columns: 
  age : int
  workclass : category
  fnlwgt : int
  education : category
  education_num : int
  marital_status : category
  occupation : category
  relationship : category
  race : category
  sex : category
  capital_gain : int
  capital_loss : int
  hours_per_week : int
  country : category
  salary : category
numerical_columns:
  - age
  - fnlwgt
  - education_num
  - capital_gain
  - capital_loss
  - hours_per_week
categorical_columns:
  - workclass
  - education
  - marital_status
  - occupation
  - relationship
  - race
  - sex
  - country
target_column: salary