columns: 
  age : int
  workclass : category
  fnlwgt : int
  education : category
  education-num : int
  marital-status : category
  occupation : category
  relationship : category
  race : category
  sex : category
  capital-gain : int
  capital-loss : int
  hours-per-week : int
  country : category
  salary : category
numerical_columns:
  - age
  - fnlwgt
  - education-num
  - capital-gain
  - capital-loss
  - hours-per-week
categorical_columns:
  - workclass
  - education
  - marital-status
  - occupation
  - relationship
  - race
  - sex
  - country
target_column: salary